Feature/nxl 7901073043 gif save
Panguino/NexLab_Client pull request #53
Opened 2024-12-04 09:42 UTC by elusiveuphoria

## Monday.com Item

Monday Item ID: 7901073043

## Description

Content and preliminary input fields created for GIF save component. Actual GIF generation still needs to be built; successful saves will output filename to console. Using short test array of images as in lieu of data call.

## How Has This Been Tested?

Tested in storybook. Use `npm run storybook` or view preview.

## Screenshots/GIF (if appropriate):
![savegif1](https://github.com/user-attachments/assets/b98b443f-9a79-4102-b0c9-eb3be6509d06)
![savegif2](https://github.com/user-attachments/assets/eec7656f-4b65-4905-9020-0b461006ea87)
![savegif3](https://github.com/user-attachments/assets/17c1cf03-7b1b-4b6a-8ce7-43ad3f0ead05)
![savegif4](https://github.com/user-attachments/assets/82d3f8fa-5108-416d-be42-c08ae178d666)

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [X] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2024-12-04 11:48 UTC, Panguino requested changes
I think we could utilize our button component on this.  I am also wondering if this is an opportunity to create an Input component that we re-use in other places we need it.   If you feel like doing that go for it, I will leave that optional.

2024-12-10 11:17 UTC, elusiveuphoria commented
@Panguino Review changes based on feedback. Input field broken out into separate component, Button component updated for use in this scenario. Concern mainly with Button, please verify other uses of the Button are unaffected (eg Academics landing, etc).

2024-12-11 13:47 UTC, Panguino requested changes
@elusiveuphoria please create storybook stories for the button and input component

2024-12-12 10:47 UTC, elusiveuphoria commented
Acted on feedback, see updates to branch. @Panguino

2024-12-13 21:28 UTC, Panguino requested changes
Just 1 change then ready to merge

2024-12-13 21:28 UTC, Panguino commented on src/components/elements/InputText/InputText.tsx
> +import React from 'react'
I think this component is fine, we can always visit this later my only ask is rename it to just `Input` not `InputText`

2024-12-16 13:34 UTC, merged